// Generated by CoffeeScript 2.3.2
(function() {
  //...........................................................................................................
  var CND, _xrpr, inspect;

  CND = require('cnd');

  ({inspect} = require('util'));

  this.assign = Object.assign;

  this.jr = JSON.stringify;

  this.flatten = CND.flatten;

  _xrpr = function(x) {
    return inspect(x, {
      colors: true,
      breakLength: 2e308,
      maxArrayLength: 2e308,
      depth: 2e308
    });
  };

  this.xrpr = function(x) {
    return (_xrpr(x)).slice(0, 1025);
  };

  this.js_type_of = function(x) {
    return ((Object.prototype.toString.call(x)).slice(8, -1)).toLowerCase();
  };

  //-----------------------------------------------------------------------------------------------------------
  this.get_rprs_of_tprs = function(tprs) {
    /* `tprs: test parameters, i.e. additional arguments to type tester, as in `multiple_of x, 4` */
    var rpr_of_tprs, srpr_of_tprs;
    rpr_of_tprs = (function() {
      switch (tprs.length) {
        case 0:
          return '';
        case 1:
          return `${rpr(tprs[0])}`;
        default:
          return `${rpr(tprs)}`;
      }
    })();
    srpr_of_tprs = (function() {
      switch (rpr_of_tprs.length) {
        case 0:
          return '';
        default:
          return ' ' + rpr_of_tprs;
      }
    })();
    return {rpr_of_tprs, srpr_of_tprs};
  };

}).call(this);

//# sourceMappingURL=helpers.js.map
